
CREATE TABLE IF NOT EXISTS EVENT (
    EVENT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    EVENT_NAME VARCHAR(100) NOT NULL,
    EVENT_DATE VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS ATTENDEE (
    ATTENDEE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(100) NOT NULL,
    PHONE_NUMBER VARCHAR(100),
    EVENT_ID INTEGER NOT NULL,
    FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID)
);

CREATE TABLE IF NOT EXISTS STAFF (
    STAFF_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(100) NOT NULL,
    ROLE VARCHAR(100) CHECK (ROLE IN ('Coordinator', 'Worker', 'Supervisor', 'Manager', 'Security', 'Volunteer')) NOT NULL,
    EVENT_ID INTEGER NOT NULL,
    FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID)
);

CREATE TABLE IF NOT EXISTS SCHEDULE (
    SCHEDULE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    START_DATE VARCHAR(100) NOT NULL,
    END_DATE VARCHAR(100) NOT NULL,
    EVENT_ID INTEGER NOT NULL,
    FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID)
);

CREATE TABLE IF NOT EXISTS TASK (
    TASK_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(100) NOT NULL,
    EVENT_ID INTEGER NOT NULL,
    FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID)
);

CREATE TABLE IF NOT EXISTS VENUE (
    VENUE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    VENUE_NAME VARCHAR(100) NOT NULL,
    LOCATION VARCHAR(100) NOT NULL,
    CAPACITY INTEGER CHECK (CAPACITY >= 0)
);

CREATE TABLE IF NOT EXISTS VENDOR (
    VENDOR_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(100) NOT NULL,
    AVAILABILITY VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS SUPPLIES (
    SUPPLY_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SUPPLY_NAME VARCHAR(100) NOT NULL,
    QUANTITY INTEGER CHECK (QUANTITY >= 0),
    VENDOR_ID INTEGER NOT NULL,
    EVENT_ID INTEGER NOT NULL,
    FOREIGN KEY (VENDOR_ID) REFERENCES VENDOR(VENDOR_ID),
    FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID)
);

CREATE TABLE IF NOT EXISTS WEATHER_CONDITION (
    DATASET_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TEMPERATURE REAL CHECK (TEMPERATURE BETWEEN -50 AND 50),
    HUMIDITY REAL CHECK (HUMIDITY BETWEEN 0 AND 100),
    EVENT_ID INTEGER NOT NULL,
    FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID)
);
